[build]
  command = "npm run build"
  publish = ".next"  # Change to .next for Next.js apps with SSR or dynamic routing
  functions = "netlify/functions"

[[redirects]]
  from = "/old-url"
  to = "/new-url"
  status = 301
  force = true
